FROM node:lts as tunnel
ARG LOCALTUNNEL_HOST
ARG LOCALTUNNEL_LOCAL_HOST
ARG LOCALTUNNEL_PORT
ARG LOCALHOST_SUBDOMAIN
ENV LOCALTUNNEL_HOST=${LOCALTUNNEL_HOST}
ENV LOCALTUNNEL_LOCAL_HOST=${LOCALTUNNEL_LOCAL_HOST}
ENV LOCALTUNNEL_PORT=${LOCALTUNNEL_PORT}
ENV LOCALHOST_SUBDOMAIN=${LOCALHOST_SUBDOMAIN}
COPY /index.js /app/
RUN cd /app && npm install localtunnel
WORKDIR /app
CMD ["node", "index.js"]

